apiVersion: v1
kind: Template
labels:
  app: lemonldap
  template: lemonldap-buildconfig
message: |-
  For more information about using this template, see https://github.com/Worteks/wsweet-ci
metadata:
  annotations:
    description: LemonLDAP-NG - BuildConfig
      see https://github.com/Worteks/docker-lemonldap
    iconClass: icon-perl
    openshift.io/display-name: LemonLDAP-NG
    openshift.io/documentation-url: https://github.com/Worteks/wsweet-ci
    openshift.io/provider-display-name: Worteks
    openshift.io/support-url: https://www.worteks.com
    tags: lemonldap-ng,lemonldap,lemon,openldap,ldap,sso
  name: lemonldap-buildconfig
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Wsweet LemonLDAP images
    labels:
      name: lemon-${FRONTNAME}-${LLNG_REPOSITORY_REF}
    name: lemon-${FRONTNAME}-${LLNG_REPOSITORY_REF}
  spec:
    failedBuildsHistoryLimit: 1
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
    source:
      contextDir: /
      git:
        uri: ${LLNG_REPOSITORY_URL}
        ref: "${LLNG_REPOSITORY_REF}"
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: DO_UPGRADE
          value: foo
        forcePull: false
        from:
          kind: ImageStreamTag
          name: ${APACHE_IMAGESTREAM_TAG}
    output:
      to:
        kind: ImageStreamTag
        name: lemon-${FRONTNAME}:${LLNG_REPOSITORY_REF}
    triggers:
    - type: ImageChange
    - type: ConfigChange
parameters:
- name: APACHE_IMAGESTREAM_TAG
  description: Set this to Apache ImageStream tag serving as base for PHP BuildConfig
  displayName: Apache ImageStream Tag
  required: true
  value: apache-wsweet:master
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
- name: LLNG_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  required: true
  value: master
- name: LLNG_REPOSITORY_URL
  description: The URL of the repository with your LemonLDAP Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/Worteks/docker-lemonldap.git
