apiVersion: v1
kind: Template
labels:
  app: lemonldap
  template: lemonldap-imagestream
message: |-
  For more information about using this template, see https://github.com/Worteks/wsweet-ci
metadata:
  annotations:
    description: LemonLDAP-NG - ImageStream
      see https://github.com/Worteks/docker-lemonldap
    iconClass: icon-perl
    openshift.io/display-name: LemonLDAP-NG
    openshift.io/documentation-url: https://github.com/Worteks/wsweet-ci
    openshift.io/provider-display-name: Worteks
    openshift.io/support-url: https://www.worteks.com
    tags: lemon,lemonldap,llng
  name: lemonldap-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in Wsweet LemonLDAP image
    name: lemon-${FRONTNAME}
parameters:
- name: FRONTNAME
  description: The name identifier assigned to objects defined in this template
  displayName: Name
  required: true
  value: demo
